name: Advent of Code 2015 ⭐
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight
    - cron: "0 6 * * *" # Every day at six
    - cron: "0 12 * * *" # Every day at noon
    - cron: "0 18 * * *" # Every day at eighteen
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.USER_ID }}
          leaderboardId: ${{ secrets.LEADERBOARD_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION }}
          tableMarker: "<!--- advent_readme_stars table 2015--->"
          year: 2015
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars